# 启动命令 进入到auto-start所在的目录 先赋权 chmod 777 auto-start
# nohup ./auto-start &
# 观察nohup.out日志文件不生成新的信息即可
# 问题反馈https://github.com/RockyFu267/auto-start

###############################################################

# 间隔时间
interval: 5
service:
    # 服务端口
  - port: 30011
    # 服务启动脚本路径  
    startpath: /app/pmdata/bin/30011-start.sh
  - port: 30021
    startpath: /app/pmdata/bin/30021-start.sh
  - port: 30031
    startpath: /app/pmdata/bin/30031-start.sh
  - port: 30041
    startpath: /app/pmdata/bin/30041-start.sh
  - port: 8666
    startpath: /app/pmdata/bin/54257-mongos-start.sh